name: Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 16 ,18 ] 
    needs: lint
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.version }}
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test
    
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: build procjekt
        run: npm run build

  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo ${{ secrets.TEST_SECRET }}

        
        
