name: Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: build procjekt
        run: npm run build
        
        

        
        
